services:
  bootroot-http01:
    networks:
      default:
        aliases:
          - 001.bootroot-agent.bootroot-agent.trusted.domain
          - 001.edge-proxy.edge-node-01.trusted.domain
          - 001.web-app.web-01.trusted.domain
