global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "step-ca"
    metrics_path: /metrics
    static_configs:
      - targets: ["step-ca:9102"]

  - job_name: "openbao"
    metrics_path: /v1/sys/metrics
    params:
      format: ["prometheus"]
    static_configs:
      - targets: ["openbao:9101"]
